language: python
dist: xenial
python:
- '3.6'
- '3.7'
install:
- pip install .
script:
- python setup.py test
cache: pip
deploy:
  provider: pypi
  user: rapiddevsolutions
  password:
    secure: TL2AEWTt/gsBbVLq5UbKGpgCHICwk0bRuZQQjNMilvDb/RDjJBRbUfH+CB/OqWLiAMkzlHE6KiAyuotawMoBLYz74V9pyqvydH24GDZTmw8UPQQCUyZbgU67E5KkZFW2MNdZHB3jCfvz0NvHlbVSEtHYTLeyIJll91PM2of7vdwx/JfBcmjiSK4Gd7/iFORtn4muylvd0n3fETBLFVVs7XdEtTeWwZo7BbKEY51fksvlc7HdJyvrZuhEPHYP712gBV0f3DTuNr+vuJ5WuqBQiOCAtgPe/P6cPFKxmlZ5mEfIzRzmj1nRngK9kr2EMFn7GsY+tUVZYHOgNeLm1CNcIeLnSi2Uz34Sa65cRA0mfXkpVL5JEM564m5JmmtE2RNbdDw9pNzkpNAwHclwuW4LcbiwyTJmoybcoe2sH99ghu1CoASECb9uYcOEpknIOsiEg44Mdq72TZvZj4GFk6HIVEHn4/BEczhC7VnGEA6zh7oSNf+Wd4qusuro6HBEdpxk97ixeMikvrZSSe+qmvWbSqmWUvjPajS4Xbez1Df9DU7pb5M2I8xqPhpi8nEajFxwcpJTp4x93husOTnRKZIC+aHgzXoBykj8mEkJzSZAncKF6fLznFshVJ6evQN0aiMUKa33mn85h3Y1T82/hn8YHDf/gjOpvX9HFvsht43vxck=
  on:
    tags: true
