version: '3'

services:
  web:
    build: ./traffic_analyzer_api
    expose:
      - "8000"
    env_file:
      - .env
    command: /usr/local/bin/gunicorn -w 3 -b :8000 app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - web